### ISSUE TITLE
PDF/Zip errors

### ISSUE THREAD

**Issue by ImageProjector** [donutdan4114/box-view-api#4]
Hi, getting the hang of this API, much easier than working with the CURL stuff directly so thanks a ton for it.

This is an example showing a local file upload which might be handy in the readme (sorry, never used Github so not sure if I should enter it directly somewhere else).

$doc = new Box_View_Document(array(
  'name' => 'test document',
     'type' => 'document',
  'file_path' => 'CV_Template1.doc',
));

I also found sleep(10); was very useful before checking to view the document. Is there a better way?

However my main problem is retrieving PDF/Zip copies of the file. Is it a premium feature? I receive the error 

Notice: Undefined property: stdClass::$zip

when copying and pasting the examples from the readme. a sample of the code follows (this shows the iframe with the document, and the error above):

$box->view($doc);
$html = '<iframe src="' . $doc->session->url . '" style="width: 800px; height: 600px;"></iframe>';
echo $html;

$box->getZip($doc);
sleep(10);
file_put_contents($doc->name . '.zip', $doc->content->zip);

I even added the sleep 10 in case it takes a while to get the zip ready. I get a zip size 0, same with a pdf (or an error if I output to browser).

Any help would be much appreciated.

**Comment by ImageProjector** [comment]
Also I think I added the 'type' => 'document', argument into the array to clear another error I was getting

**Comment by donutdan4114** [comment]
I've updated the README.md to include the `file_path` example (9af72b26).
As far as the `sleep(10)` thing goes, you are able to check the file's `status` when you use `$box->getMetaData($doc)`.

You can also setup [webhooks](http://developers.box.com/view/webhooks/), where Box will ping you when a document has finished uploading.

I don't believe getting the zip/pdf is premium feature. You should be able to do `$box->getPDF($doc)` and that retrieves the raw pdf output (not a file).

If you still have issues, send me the exact code you are using so I can test, thanks.
